apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gatus.name" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gatus.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "5"
data:
  config.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}

