apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/fapiper/fabianpiper.com.git'
    path: provisioning/argocd/infrastructure
    targetRevision: HEAD
    directory:
      recurse: true # Include nested applications
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true