#cloud-config
package_update: true
packages:
  - curl
  - iptables-persistent

write_files:
  - path: /etc/rancher/k3s/registries.yaml
    owner: root:root
    permissions: '0644'
    content: |
      configs:
        ghcr.io:
          auth:
            username: ${git_username}
            password: ${git_pat}

runcmd:
  # Configure iptables
  - iptables -P INPUT ACCEPT
  - iptables -P FORWARD ACCEPT
  - iptables -F INPUT
  - iptables -F FORWARD
  - netfilter-persistent save

  # Install K3s server
  - |
    curl -sfL https://get.k3s.io | sh -s - server \
      --token ${k3s_token} \
      --tls-san ${public_ip} \
      --disable traefik \
      --disable servicelb \
      --node-label role=server

  # Wait for K3s to be ready
  - sleep 30
  - k3s kubectl wait --for=condition=Ready nodes --all --timeout=300s

  # Create ArgoCD namespace
  - k3s kubectl create namespace argocd

  # Install ArgoCD core manifests
  - k3s kubectl apply --server-side -k https://github.com/argoproj/argo-cd/manifests/crds?ref=v3.3.0
  - k3s kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/v3.3.0/manifests/install.yaml

  # Wait for ArgoCD CRDs to be established
  - sleep 10
  - k3s kubectl wait --for=condition=established --timeout=300s crd/applications.argoproj.io
  - k3s kubectl wait --for=condition=established --timeout=300s crd/applicationsets.argoproj.io

  # Force restart the applicationset-controller to clear a startup crash loop
  - k3s kubectl rollout restart deployment/argocd-applicationset-controller -n argocd

  # Wait for ArgoCD pods to be ready
  - k3s kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd
  - k3s kubectl wait --for=condition=available --timeout=600s deployment/argocd-repo-server -n argocd
  - k3s kubectl wait --for=condition=available --timeout=600s deployment/argocd-applicationset-controller -n argocd

  # Configure ArgoCD Git credentials
  - |
    k3s kubectl apply -f - <<EOF
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-github-repo
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
    type: Opaque
    stringData:
      type: git
      url: ${git_repo_url}
      username: ${git_username}
      password: ${git_pat}
    EOF

  # Ensure the application-controller is also ready
  - k3s kubectl wait --for=condition=available --timeout=600s deployment/argocd-application-controller -n argocd

  # Deploy root application
  - sleep 5
  - curl -sfL https://raw.githubusercontent.com/fapiper/fabianpiper.com/main/kubernetes/bootstrap/root.yaml | k3s kubectl apply -f -