apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.grafanaAdmin.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kps-wrapper.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: {{ .Values.grafanaAdmin.secretName }}
    template:
      data:
        {{ .Values.grafanaAdmin.userKey }}: "admin"
        {{ .Values.grafanaAdmin.passwordKey }}: '{{ "{{" }} .grafanaAdminPassword | trim {{ "}}" }}'
  data:
    - secretKey: grafanaAdminPassword
      remoteRef:
        key: grafana-admin-password
