helm:
  parameters:
  - name: image.repository
    value: ghcr.io/fapiper/fabianpiper.com/www
    forcestring: true
  - name: image.tag
    value: latest@sha256:fa91b7a88456d7750e9c66f8bd608a188e467ab99105c504e3fce97fc388cc36
    forcestring: true
