helm:
  parameters:
  - name: image.repository
    value: ghcr.io/fapiper/fabianpiper.com/www
    forcestring: true
  - name: image.tag
    value: latest@sha256:32fa70097287fbd65a049e1dc01f2411e404be9d1c98c70dcf5eb7a514a2830b
    forcestring: true
