replicaCount: 2

image:
  repository: ghcr.io/fapiper/fabianpiper.com/www
  tag: latest
  digest: ""
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  hostname: www.fabianpiper.com
  secondaryHostname: glg.fabianpiper.com
  gatewayNamespace: envoy-gateway-system
  redirectHostnames:
    - www.fabianpiper.com
    - glg.fabianpiper.com
    - grafana.fabianpiper.com
    - status.fabianpiper.com

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

