apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: "${vault_ocid}"
      region: "eu-frankfurt-1"
      principalType: InstancePrincipal