apiVersion: v1
kind: ConfigMap
metadata:
  name: oci-vault-config
  namespace: external-secrets
data:
  vault_ocid: "" # This will be populated by cloud-init during cluster setup
  region: "eu-frankfurt-1"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: oci-vault
spec:
  provider:
    oracle:
      vault: "" # Vault OCID will be set via cloud-init
      region: "eu-frankfurt-1"
      principalType: InstancePrincipal