apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.tls.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "www.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "18"
spec:
  secretName: {{ .Values.tls.secretName }}
  issuerRef:
    name: {{ .Values.tls.issuerName }}
    kind: {{ .Values.tls.issuerKind }}
  commonName: {{ .Values.ingress.hostname | quote }}
  dnsNames:
    - {{ .Values.ingress.hostname | quote }}

