apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "www.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "www.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "www.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "www.labels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ include "www.name" . }}
          image: {{ include "www.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

