apiVersion: v1
kind: Service
metadata:
  name: {{ include "www.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "www.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  selector:
    {{- include "www.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  type: ClusterIP

