apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: www-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: www=ghcr.io/fapiper/fabianpiper.com/www
    argocd-image-updater.argoproj.io/www.update-strategy: newest-build
    argocd-image-updater.argoproj.io/www.allow-tags: regexp:^(latest|sha-[a-f0-9]{40})$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/fapiper/fabianpiper.com.git # Replace with your Git repository URL
    targetRevision: HEAD
    path: argocd/apps/www
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
