import:
  - mixins/stage/prod
  - mixins/region/fra

vars:
  tenant: "hs"
components:
  terraform:
    k3s-cluster:
      vars:
        # These will be set after `make apply-prod-networking`:
        # vcn_id: "ocid1.vcn.oc1.eu-frankfurt-1.xxx"
        # public_subnet_id: "ocid1.subnet.oc1.eu-frankfurt-1.xxx"

        common_tags:
          Environment: "${environment}"