apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: external-dns
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
    template:
      data:
        api-token: "{{ .api_token | trim }}"
  data:
    - secretKey: api_token
      remoteRef:
        key: cloudflare-api-token

