apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: business-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fapiper/fabianpiper.com.git
    targetRevision: HEAD
    path: provisioning/argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true