apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: regcred-sync
  namespace: www
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: oci-vault
    kind: ClusterSecretStore
  target:
    name: regcred
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "${git_username}",
                "password": "{{ .github_pat }}",
                "auth": "{{ printf "%s:%s" "${git_username}" .github_pat | b64enc }}"
              }
            }
          }
  data:
    - secretKey: github_pat
      remoteRef:
        key: github-pat