#cloud-config
package_update: true
packages:
  - curl
  - iptables-persistent

write_files:

  - path: /etc/rancher/k3s/registries.yaml
    owner: root:root
    permissions: '0644'
    content: |
      configs:
        ghcr.io:
          auth:
            username: ${git_username}
            password: ${git_pat}

runcmd:
  # Configure iptables
  - iptables -P INPUT ACCEPT
  - iptables -P FORWARD ACCEPT
  - iptables -F INPUT
  - iptables -F FORWARD
  - netfilter-persistent save

  # Install K3s server
  - |
    curl -sfL https://get.k3s.io | sh -s - server \
      --token ${k3s_token} \
      --tls-san ${public_ip} \
      --disable traefik \
      --disable servicelb \
      --node-label role=server

  # Wait for K3s to be ready
  - sleep 30
  - k3s kubectl wait --for=condition=Ready nodes --all --timeout=300s

  # Install ArgoCD using kustomize (includes namespace and all CRDs)
  - |
    cat > /tmp/argocd-bootstrap.yaml <<'EOFKUSTOMIZE'
    apiVersion: kustomize.config.k8s.io/v1beta1
    kind: Kustomization
    namespace: argocd
    resources:
      - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/namespace-install.yaml
    EOFKUSTOMIZE
  - k3s kubectl apply -k /tmp/argocd-bootstrap.yaml

  # Wait for ArgoCD to be ready
  - sleep 15
  - k3s kubectl wait --for=condition=available --timeout=600s deployment/argocd-server -n argocd || true
  - k3s kubectl wait --for=condition=available --timeout=600s deployment/argocd-repo-server -n argocd || true
  - k3s kubectl wait --for=condition=available --timeout=600s deployment/argocd-applicationset-controller -n argocd || true

  # Configure ArgoCD Git credentials
  - |
    k3s kubectl apply -f - <<EOF
    apiVersion: v1
    kind: Secret
    metadata:
      name: argocd-github-repo
      namespace: argocd
      labels:
        argocd.argoproj.io/secret-type: repository
    type: Opaque
    stringData:
      type: git
      url: ${git_repo_url}
      username: ${git_username}
      password: ${git_pat}
    EOF

  # Deploy root application (bootstraps everything via ApplicationSets)
  - curl -sfL https://raw.githubusercontent.com/fapiper/fabianpiper.com/main/kubernetes/bootstrap/root.yaml | k3s kubectl apply -f -

